### ISSUE TITLE
IR Signal doesn`t work / bad output signal

### ISSUE THREAD

**Issue by Superhelmi** [unfoldedcircle/bug-reports#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The IR output signal from the dock output plugs is bad.
Also the IR emitter inside the doc are very very weak !!
So IR isn`t working !!

### How to Reproduce

look at the signal with an oszilloskop at IR OUT and press a button

![Remote2 Lauter](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/7073581/f63a65bb-0cf9-4074-b650-0cb4e76a781e)

Output without an signal:

![Remote2 Leerlauf](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/7073581/ff3d458d-9948-4366-a399-f83ecb221612)

The fundamental big signal is about 50Hz !

### Expected behavior

I expect IR to work !!

### System version

0.9.2

### What part of the system affected by the problem?

Overall system

### Additional context

On the Geman part of the discord forum there are more that have this problem that IR doesn`t work or is extremly weak !! (Also in other english parts)

**Comment by Superhelmi** [comment]
Not Discord... the Unfolded Circle Forum !

**Comment by lutzh86** [comment]
Hi @Superhelmi,

I saw your report about the weak IR signal from the dock, and I'm on the case. To get to the bottom of this, I need to understand how you tested things. Right now, your results are puzzling because our setup should prevent such problems.

Here's the deal: our system uses an N-channel Mosfet for switching, and there's always a steady 5V on the high side. So, your 50 Hz reading? That's probably noise from your home's electrical lines, not a fault in the dock.

Also, the 68-ohm resistor on the low side is there to keep power levels in check. It's all designed to work together, so something odd is happening if you're seeing these issues.

Can you give more details on how you measured the IR signal? What tools and settings did you use, and what was happening around you at the time?

About the IR strength: I hear you, but I need solid data to understand what's going on. If you can provide more specifics on your test setup, it'll help us figure out whether it's a real issue with the device or something else in the environment.
But please keep in mind, our IR-Extenders are meant to be used directly in front of devices, these are not IR-Blasters. 

best regards
Lutz

**Comment by Superhelmi** [comment]
Hi Lutz, 

I measured the output signal directly (voltage) with an DSO at the open end of a mono jack line. 
Same settings, same DSO device and measurement line but at the IR Output of an AV Pre:


![Image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/7073581/f745df8c-cd06-4de2-8071-47d5700ad3d2)

What signal is to expect at the IR output jacks ? Do I have to connect a resistor to get a prober outputsignal ?

best regards
Markus

**Comment by martonborzak** [comment]
Closing as this has been answered, unfortunately only in German: https://unfolded.community/t/deutsches-forum/638/77
