### ISSUE TITLE
Showing wrong wifi name when setup

### ISSUE THREAD

**Issue by tastyrepublic** [unfoldedcircle/bug-reports#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When wifi SSID include the (‘s) character , the remote two can’t show it correctly, and can’t connect to it.

### How to Reproduce

1. Search for wifi in remote two setup page.

### Expected behavior

Show wifi name that’s include (‘s) character.

### System version

V1.4.3

### What part of the system affected by the problem?

Core

**Comment by zehnm** [comment]
Which character is that exactly?

**Comment by tastyrepublic** [comment]
> Which character is that exactly?

Wifi name: Don’s wifi
But it show up like: Don\xe2\x80\x99s wifi
I never saw this in other devices.

**Comment by martonborzak** [comment]
Please note also that newer firmware is available.

**Comment by tastyrepublic** [comment]
> Please note also that newer firmware is available.

Just updated to the latest version now by connecting to other wifi, problem still there.

**Comment by zehnm** [comment]
It's a Unicode encoding issue: `\xe2\x80\x99` is UTF-8 for 


U+2019 | ’ | \xe2\x80\x99 | RIGHT SINGLE QUOTATION MARK
-- | -- | -- | --

So there's a missing encoding when retrieving the names... Sorry about that!
Let me setup my spare access point for testing 🤓

**Comment by tastyrepublic** [comment]
Thank you for testing it out.

**Comment by tastyrepublic** [comment]
So can I expect it will be fix at the next update? I still waiting to connect to the wifi so I can control my Apple TV and hue setup.

**Comment by zehnm** [comment]
We are working with high priority on this showstopper. It's much more complex than a simple encoding, which turned out not to be the issue. The wifi driver is already messing with the SSID name, if it doesn't contain plain text (anything else than ASCII 7-bit), and performs it's own character escaping.

The first fix will work with proper UTF-8 SSID names, as your network name.
However, there's much more to it, thanks to the "very special" SSID specification. Not many access points support such network names, but since we're at it, we try to get this covered as well.

**Comment by tastyrepublic** [comment]
Really don’t know it need quite some works to fix it. Keep the great work👍🏻wait for the update.

**Comment by zehnm** [comment]
Closing: fixed in release 1.4.5
SSID with proper UTF-8 names are now working.

Restrictions:
- non-UTF-8 SSIDs are not yet supported in the UI.
  (Most access points don't support using arbitrary byte characters in the SSID name, and IMHO shouldn't be used anyways 😅)
- emojis are not supported.

**Comment by tastyrepublic** [comment]
Thank you so much. Will test it out.
