### ISSUE TITLE
Invalid or missing params.sound_mode attribute when Sound mode command is assigned to a button and the button is pressed

### ISSUE THREAD

**Issue by fbutler** [unfoldedcircle/bug-reports#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I mapped the Sound mode command to a "Movie" button in an Activity and assigned a Mode of MOVIE from the drop down list of available Modes. This appears to be correctly saved as the Mode assigned remains associated with the button if I move away from that screen and return to it.

![invalid or missing params sound_mode attribute](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/1867723/f529b60b-cd0a-4537-8e97-57ad12fb78c1)

However when I press the "Movie" button, to which the Sound mode command has been associated, when running that Activity  I get the error "Invalid or missing params.sound_mode attribute"

![20231103_141315](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/1867723/8974c220-2d77-4ede-9e7e-68f306eb70f3)

### How to Reproduce

Go to the button mapping screen within an Activity. 
Assign the Sound mode command to a button.
Select a Mode from the drop down list of available Modes.
Exit the button mapping dialogue.
Start that Activity using the remote.
Press the button that the Sound mode command is assigned to.
See the error as per the photo above.

### Expected behavior

When pressed, the button assigned the Sound mode command should result in the assigned Mode being applied.

In the case of my Denon AVR this should result in a menu of available sound options for the Mode selected being displayed on the TV screen which can be scrolled through by repeatedly clicking the button to which the Sound mode command has been assigned.

I have a Home Assistant script mapped to another button which functions correctly. The script is:

![image](https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/1867723/7d72bbd9-ca67-4fcd-ba07-ac77c5818bba)

 

### System version

1.4.5

### What part of the system affected by the problem?

Integration

**Comment by zehnm** [comment]
Found the issue, fixed in the next release.

- Home Assistant integration was implemented according to the [media-player entity command specification 0.8.0](https://github.com/unfoldedcircle/core-api/blob/v0.8.0-alpha/doc/entities/entity_media_player.md#commands)
  - Selecting a sound mode defines a parameter named `sound_mode` 
- Unfortunately the command metadata for the web-configurator used `mode` instead of `sound_mode`.
  - This parameter gets stored in the sequences and UI screen definitions.

I will change the entity command specification to `mode` and fix the Home Assistant integration. It's the most pragmatic solution, otherwise all activity screens, macro and activity sequences using a sound mode command, would become invalid. Doing a data migration is way more work and riskier...

**Comment by fbutler** [comment]
Thanks

Fergal

**Comment by zehnm** [comment]
Status: fix is released in the BETA group and available later this week if we don't find any showstopper.

**Comment by zehnm** [comment]
Fixed in the just released v1.4.8 update
