### ISSUE TITLE
Home Assistant Integration - Scripts

### ISSUE THREAD

**Issue by splattner** [unfoldedcircle/bug-reports#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not sure if a Bug or just not implemented but: I use a lot of Scripts in Home Assistant and it seems they are not show in the integration configuration. Should they appear under "Macro" or "Activities" in the Home Assistant Integration Configuration?

### How to Reproduce

Filter by type in the Home Assistant Integration to "Macro" or "Activities" and nothing is shown alought I have 20+ scripts in HA

### Expected behavior

Maybee its just not (yet) implemented, but I expect them to be shown there somewhere

### System version

v1.1.1

### What part of the system affected by the problem?

Integration

**Comment by splattner** [comment]
Looking at the code in https://github.com/unfoldedcircle/integration-home-assistant I guess its just not (yet?) implemented. I try to play with the Universal Media Player now to cover my usecase.

**Comment by zehnm** [comment]
Correct, HA scripts are not yet supported. 
I quickly checked creating a script in HA and running it. The script & state changes are reported in the HA WS API 👍 and the integration reports `Unsupported entity: script`.
I'll check if triggering from Remote Two also works (the HA API sometimes requires some tinkering). Then I could map the HA scripts to a button entity, so that they could at least be triggered from the remote.
Exposing them as a macro requires more investigation and probably quite a few changes. As far I see from the reported data, the HA script internals are not visible with the WS API (e.g. how many steps or involved entities), only if it's currently active or not.

**Comment by zehnm** [comment]
Dependeny for scripts mapped to an `input_button` entity:
- #13

@splattner would triggering scripts with a button entity be sufficient for you, or do you also require to see the active state of the script?

I'll play around a bit, it also seems possible to `turn off` a running script. A switch button might be a better choice for scripts in this case.

**Comment by splattner** [comment]
Triggering a script with a button would be totally find and I'm also already playing around with the home-assistant integration and I think I almost have a running solution. But to be fair, its the first time with Rust for me ;)

**Comment by splattner** [comment]
Something like that https://github.com/unfoldedcircle/integration-home-assistant/pull/20

**Comment by zehnm** [comment]
Triggering scripts is included in firmware release 1.2.0
