### ISSUE TITLE
[bug] Rapid Update causing extreme lags

### ISSUE THREAD

**Issue by Sledgehamma** [unfoldedcircle/bug-reports#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using a HA integration (with rapid update) it seems to cause extreme lag and stutter on the remote itself. Touch and key input has a huge delay and animations stutter extremely. 
When I stop playback, and therefore no progress syncing appears, everything is back to normal and the remote is responsive. In addition, when there is no backdrop, no lagging occours. 

I also created a bug report for the integration itself and the developer suggested that the cause may be the rapid update:
"Its most likely associated with rapid update. Lovelace is pretty good at only updating the frontend if a state value has actually changed. Its possible the Unfolded firmware is trying to refresh things on every event. for example, it maybe downloading and redrawing the backdrop image every update event."
https://github.com/wizmo2/zidoo-player/issues/24

### How to Reproduce

1. Use a HA integration with rapid update
2. start playback
3. remote extremely laggy

### Expected behavior

No lag as with other integrations.

**Comment by martonborzak** [comment]
It's bit weird that integration is sending updates even when nothing changed, but we've added a safeguard in the UI to double check data before updating.

**Comment by Talkabout** [comment]
Hi guys,

with the new firmware I noticed that in my case the image on the remote does not change any more. This seems to be related to the new "safeguard". My media player has the same URL, regardless of what is actually running. I stored the URl in an attribute and simply am providing this information in the "entity_change" event. Now, because same URLs are not reloaded, I do not see the current image but the old one. Is there a way to skip the "safeguard"?

Thanks!

**Comment by Talkabout** [comment]
Hi,

I was able to change my logic and append a unique argument for every content shown. It seems to work.

**Comment by martonborzak** [comment]
Fixed in 1.7.4.

**Comment by Sledgehamma** [comment]
yep, its fixed :)
Thanks a lot unfolded circle team!
