### ISSUE TITLE
Android TV long press

### ISSUE THREAD

**Issue by RomRider** [unfoldedcircle/bug-reports#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Android TV "OK"/"SELECT" central button should not auto-repeat but instead make it so that you can long press an item on screen.

### How to Reproduce

1. Integrate an Android TV
2. Run an app which supports long press
3. Try to long press the item with the central button
4. It will just click in repeat mode instead of long pressing the item

### Expected behavior

Pressing the central button while maintaining it should run the long press command.

### System version

1.2.1

### What part of the system affected by the problem?

Core, Integration

**Comment by OverloadUT** [comment]
I suggest updating the Expected Behavior to say that all buttons should issue a long-press command, as there are other pieces of functionality (in Shield TV for example) that require long-pressing, such as the home button and the menu button

**Comment by NovaRagnarok** [comment]
> I suggest updating the Expected Behavior to say that all buttons should issue a long-press command, as there are other pieces of functionality (in Shield TV for example) that require long-pressing, such as the home button and the menu button

Ditto for IR blasting.

**Comment by methnen** [comment]
I got at this with my ticket for Apple TV but at least in the Apple TV case the commands themselves aren't in the integration:

https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/56

**Comment by martonborzak** [comment]
We're enhancing the media player component with custom command options. This will enable the additon of commands that trigger actions, that are invoked with long presses with traditional remotes.

Short press, repeat and long presses are handled by the UI.

After this enhancement, you'll be able to assign a command to a short press and another command to a long press, basicaly achieving similar functionality as with traditional remotes, where a short and long press invokes a different action.

**Comment by zehnm** [comment]
The next release supports the new media-player features and simple commands.

New Android TV integration version will soon be released in beta channel.

**Comment by zehnm** [comment]
Included in the just released beta firmware 1.7.9 and will be part of the next public release.

To update an already configured Android TV media-player entity with the new features: click "Reload" at the bottom of the available entities pane in the web-configurator. This will load the new entity features and commands from the integration and update the configured entity.

Please note that long press actions must be configured in the web-configurator and map to an available command in the integration. By default, pressing & holding a button will repeat it, unless it's configured to a different command.

Currently the common long press commands for NVIDIA Shield TV & Google Chromecast devices are supported, like `context_menu` which maps to long-pressing DPAD_CENTER on the original remote. For all other Android TV devices there are new simple commands: `CURSOR_ENTER_LONG`, `HOME_LONG` and `MENU_LONG`.
More information: https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/command_mapping.md

With the newly introduced device profiles, more mappings can be easily defined in a configuration file (since every Android TV device is different...). User uploadable profiles and manual selection is planned, but there's no ETA yet.

**Comment by zehnm** [comment]
Included in release 1.7.12

**Comment by kschonha** [comment]
Using the Android TV Integration in support of vSeeBox V6 Plus, lacks a command that functions like the original vSeeBox remote's Cursor Left button while in the EPG (Program Guide).  The Integration's Cursor Left command works fine to scroll the Program Guide back in time, but a Long Press on the original remote's Cursor Left button will jump to the Categories column (Favorites, Entertainment, etc.) on the leftmost side of the screen allowing the Category to be changed while leaving the full Program Guide visible and available for navigation.  A command with that capability appears to be missing from the current Android TV Integration version.  

I would be very grateful to see this improvements implemented.
